// Preference screen for configuring recipe generation options and launching the result view.
package com.example.pantrychef.ui.recipe

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.layout.FlowRow
import androidx.compose.foundation.layout.ExperimentalLayoutApi
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.hilt.navigation.compose.hiltViewModel
import com.example.pantrychef.core.RecipePreferences
import com.example.pantrychef.ui.pantry.PantryViewModel

@OptIn(ExperimentalMaterial3Api::class, ExperimentalLayoutApi::class)
@Composable
fun RecipeScreen(
    viewModel: PantryViewModel = hiltViewModel(),
    onBack: () -> Unit,
    onOpenResult: () -> Unit
) {
    val scroll = rememberScrollState()

    val mealTime = remember { mutableStateListOf<String>() }
    val styleSpeed = remember { mutableStateListOf<String>() }
    val diet = remember { mutableStateListOf<String>() }
    val cuisine = remember { mutableStateListOf<String>() }
    val mood = remember { mutableStateListOf<String>() }

    val voices = listOf(
        "Playful Classic",
        "Plain (Minimal)",
        "British Pub Cook",
        "California Wellness",
        "Italian Nonna",
        "Science-y Food Nerd",
        "Street-food Storyteller",
        "Nordic Minimalist",
        "BBQ Pitmaster",
        "Kitchen Nightmare (Brutally Honest)",
        "Pirate",
        "Cute for Kids"
    )
    var selectedVoice by remember { mutableStateOf("Playful Classic") }

    var spicyLanguage by remember { mutableStateOf(false) }
    var childFriendly by remember { mutableStateOf(false) }

    var mustsText by remember { mutableStateOf("") }
    var allowAdditions by remember { mutableStateOf(true) }
    var additionsCount by remember { mutableStateOf(2f) }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("Recipe preferences") },
                navigationIcon = { TextButton(onClick = onBack) { Text("Back") } }
            )
        },
        bottomBar = {
            BottomAppBar {
                Spacer(Modifier.weight(1f))
                Button(
                    onClick = {
                        val prefs = RecipePreferences(
                            mealTime = mealTime.toList(),
                            styleSpeed = styleSpeed.toList(),
                            diet = diet.toList(),
                            cuisine = cuisine.toList(),
                            mood = mood.toList(),
                            mustInclude = mustsText.split(",").map { it.trim() }.filter { it.isNotBlank() },
                            maxNewAdditions = if (allowAdditions) additionsCount.toInt() else 0,
                            voice = selectedVoice,
                            spicyLanguage = spicyLanguage,
                            childFriendly = childFriendly
                        )
                        viewModel.setRecipePreferences(prefs)
                        viewModel.generateRecipes()
                        onOpenResult()
                    },
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(horizontal = 16.dp)
                        .height(52.dp)
                ) { Text("Generate Recipe") }
            }
        }
    ) { inner ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(inner)
                .imePadding()
                .navigationBarsPadding()
                .verticalScroll(scroll)
                .padding(horizontal = 16.dp, vertical = 12.dp),
            verticalArrangement = Arrangement.spacedBy(16.dp)
        ) {
            ElevatedCard(shape = MaterialTheme.shapes.extraLarge) {
                Column(Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) {
                    Text(
                        text = "Pick a few quick options below. You can also set must-haves and how many new ingredients are allowed.",
                        style = MaterialTheme.typography.bodyMedium,
                        color = MaterialTheme.colorScheme.onSurfaceVariant
                    )
                    Text(
                        text = "Recipes are generated by AI. We can’t guarantee accuracy, safety, or outcomes. Please use your judgment and check allergens, doneness, and food safety.",
                        style = MaterialTheme.typography.bodySmall,
                        color = MaterialTheme.colorScheme.onSurfaceVariant
                    )
                }
            }

            FilterChipSection("Meal time", listOf("Breakfast","Brunch","Lunch","Dinner","Late-night snack"), mealTime)
            FilterChipSection("Style & speed", listOf("15-minute","30-minute","One-pot","Sheet-pan","Air fryer","No oven"), styleSpeed)
            FilterChipSection("Diet", listOf("Vegetarian","Vegan","Pescatarian","High-protein","Low-carb","Gluten-free","Dairy-free"), diet)
            FilterChipSection("Cuisine", listOf("Italian","Mexican","Indian","Thai","Chinese","Japanese","Mediterranean","French","American","Middle Eastern"), cuisine)
            FilterChipSection("Mood", listOf("Comfort food","Light & fresh","Spicy","Meal prep"), mood)

            ElevatedCard {
                Column(Modifier.padding(16.dp)) {
                    Text("Must include", style = MaterialTheme.typography.titleMedium)
                    Spacer(Modifier.height(8.dp))
                    OutlinedTextField(
                        value = mustsText,
                        onValueChange = { mustsText = it },
                        placeholder = { Text("e.g., tomato, garlic, basil") },
                        singleLine = false,
                        minLines = 2,
                        modifier = Modifier.fillMaxWidth()
                    )
                }
            }

            ElevatedCard {
                Column(Modifier.padding(16.dp)) {
                    Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
                        Text("Allow new additions", style = MaterialTheme.typography.titleMedium)
                        Switch(checked = allowAdditions, onCheckedChange = { allowAdditions = it })
                    }
                    Spacer(Modifier.height(8.dp))
                    val enabled = allowAdditions
                    CompositionLocalProvider(LocalContentColor provides (if (enabled) LocalContentColor.current else LocalContentColor.current.copy(alpha = 0.6f))) {
                        Column {
                            Text("Max extra ingredients: ${additionsCount.toInt()}")
                            Slider(
                                value = additionsCount,
                                onValueChange = { additionsCount = it },
                                valueRange = 0f..5f,
                                steps = 4,
                                enabled = enabled
                            )
                            Text("Salt, pepper, oil, and water don’t count.")
                        }
                    }
                }
            }

            ElevatedCard {
                Column(Modifier.padding(16.dp)) {
                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.SpaceBetween,
                        verticalAlignment = androidx.compose.ui.Alignment.CenterVertically
                    ) {
                        Text("Child-friendly (picky eaters)", style = MaterialTheme.typography.titleMedium)
                        Switch(checked = childFriendly, onCheckedChange = { childFriendly = it })
                    }
                    Spacer(Modifier.height(6.dp))
                    Text(
                        "Simpler flavors, mild heat, familiar swaps, and clear steps for kids to help.",
                        color = MaterialTheme.colorScheme.onSurfaceVariant
                    )
                }
            }

            ElevatedCard {
                Column(Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) {
                    Text("Voice", style = MaterialTheme.typography.titleMedium)
                    FlowRow(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.spacedBy(10.dp),
                        verticalArrangement = Arrangement.spacedBy(10.dp)
                    ) {
                        voices.forEach { label ->
                            val isSelected = selectedVoice == label
                            FilterChip(
                                selected = isSelected,
                                onClick = { selectedVoice = label },
                                label = { Text(label) }
                            )
                        }
                    }
                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.SpaceBetween,
                        verticalAlignment = androidx.compose.ui.Alignment.CenterVertically
                    ) {
                        Text("Spicy language (PG witty)", style = MaterialTheme.typography.bodyMedium)
                        Switch(checked = spicyLanguage, onCheckedChange = { spicyLanguage = it })
                    }
                }
            }

            Spacer(Modifier.height(88.dp))
        }
    }
}

@OptIn(ExperimentalLayoutApi::class)
@Composable
private fun FilterChipSection(
    title: String,
    chips: List<String>,
    selected: MutableList<String>
) {
    Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
        Row(
            verticalAlignment = androidx.compose.ui.Alignment.CenterVertically,
            modifier = Modifier.fillMaxWidth()
        ) {
            Text(title, style = MaterialTheme.typography.titleMedium, modifier = Modifier.weight(1f))
            TextButton(onClick = { selected.clear() }) { Text("Clear") }
        }
        FlowRow(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.spacedBy(8.dp),
            verticalArrangement = Arrangement.spacedBy(8.dp)
        ) {
            chips.forEach { label ->
                val isSelected = label in selected
                FilterChip(
                    selected = isSelected,
                    onClick = { if (isSelected) selected.remove(label) else selected.add(label) },
                    label = { Text(label) }
                )
            }
        }
        HorizontalDivider()
    }
}
